server:
  port: 8001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/asnice/config.git
          searchPaths: /config/          #
          force-pull: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eurake/